POST http://localhost:8080/api/user/connection/try
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IiIsImlhdCI6MTc2NDUwNTk4MSwiZXhwIjoxNzY0NTkyMzgxfQ.w5DwhVcSUuukRpFuljTthThxepiFyF9eRRmS9Fq8AzxA86BYZ-q1OVpbdN3qCvLyVw24l4e02Bu6Ep_HghRAhg

{
  "key": "b9c794"
}
