POST http://localhost:8080/api/user/connection/try
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IiIsImlhdCI6MTc2Mzc1MDE3MCwiZXhwIjoxNzYzODM2NTcwfQ.WSN7TckKgcy764ie0cilvmqjz9Xn5iEotCr4qScrFwHhDCuLbAgovg7ETw1pZbWdzpPxinZ_zb08W4DeU4pdtQ

{
  "key": "f433a3"
}
