POST http://localhost:8080/api/auth/signup/therapist
Content-Type: application/json

{
  "email": "asd1@asd",
  "password": "asdasdasd1",
  "name": "asd1",
  "organization": "asd1",
  "therapistType": "NURSE"
}