POST http://t2.mobidic.shop/api/auth/signup/patient
Content-Type: application/json

{
  "email": "patient@test",
  "password": "testtest1",
  "name": "김환자",
  "birthDate": "1990-01-01",
  "gender": "FEMALE"
}