POST http://localhost:8080/api/auth/signup/therapist
Content-Type: application/json

{
  "email": "therapist@test",
  "password": "testtest1",
  "name": "김간호사",
  "organization": "무슨무슨병원",
  "therapistType": "NURSE"
}